# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BP_resample <- function(waveform, origFs) {
    .Call(`_abpwaveforms_BP_resample`, waveform, origFs)
}

BP_lowpass <- function(x) {
    .Call(`_abpwaveforms_BP_lowpass`, x)
}

doubleDerive <- function(waveform) {
    .Call(`_abpwaveforms_doubleDerive`, waveform)
}

getFootIndex <- function(waveformDDPlus, zoneOfInterest) {
    .Call(`_abpwaveforms_getFootIndex`, waveformDDPlus, zoneOfInterest)
}

FixIndex <- function(footIndex, fs = 200.0, minIntervalSec = 0.3, maxIntervalSec = 2.0) {
    .Call(`_abpwaveforms_FixIndex`, footIndex, fs, minIntervalSec, maxIntervalSec)
}

getPeakIndex <- function(waveform, footIndex) {
    .Call(`_abpwaveforms_getPeakIndex`, waveform, footIndex)
}

computeSUT_PA <- function(waveform, foot, peak, fs) {
    .Call(`_abpwaveforms_computeSUT_PA`, waveform, foot, peak, fs)
}

getDicroticNotchAndPeak <- function(signal, foot, peak, fs = 200.0) {
    .Call(`_abpwaveforms_getDicroticNotchAndPeak`, signal, foot, peak, fs)
}

